### ISSUE TITLE
 full duplex supported?

### ISSUE THREAD

**Issue by guo652917087** [Lora-net/sx1302_hal#1]
Is the SX1302 software already supporting full duplex in the CN470-510 band?

**Comment by mcoracin** [comment]
No, full-duplex is not fully supported yet.

**Comment by guo652917087** [comment]
@mcoracin   I saw that the US915 has such a configuration file （ global_conf.json.us915.full_duplex）on version V1.0.0. Is the US915 already implementing full duplex?

**Comment by mcoracin** [comment]
No, full duplex is not supported for now
