### ISSUE TITLE
Update firmware to V2

### ISSUE THREAD

**Issue by jumanamirza** [Lora-net/sx1302_hal#110]
1-I am sending LR-FHSS packets using SX126x and I am trying to decode packets using this gateway "SX1302CSS915GW1".
2-On this application note, https://www.mouser.com/pdfDocs/AN1200-64_LR-FHSS_system_performance_V1_2.pdf, you said "LR-FHSS demodulation can be achieved by all V2 gateways with the applicable firmware update".
3-This code latest release is [v2.1.0]. Even that the current release of MCU is v1.0.0.

So, is this code able to demodulate LR-FHSS packets? or should i update MCU to v2? and how can i do that?

Thanks

**Comment by mcoracin** [comment]
Hello,
The sx1302 gateways cannot receive LR-FHSS packets. It is not a matter of the MCU version.
The refered "V2 gateways" is a specific gateway design with sx1301 for LoRa, and an additional FPGA+DSP for LR-FHSS demodulation. But this gateway design is not publicly available.
You need to contact semtech support for more information: support@semtech.com
Best regards,
Michael

**Comment by jumanamirza** [comment]
Thanks for your replay and clarification. I do not need to know or access the design and just need to run
the executable, would that be possible?

**Comment by mcoracin** [comment]
The issue is with the hardware, the gateway you have does not have the capability to demodulate LR-FHSS.

**Comment by jumanamirza** [comment]
Thank you for confirming that. You saved my time. One more question please, is there any gateway that is commercially available and can decode LR-FHSS packets?

**Comment by mcoracin** [comment]
Hello, unfortunately today I don't know about a commercially available gateway that supports LR-FHSS.
I know that Cisco and Kerlink at least have gateways capable of supporting it (V2 designs), but they do not provide the feature.

**Comment by jumanamirza** [comment]
Thank you so much. Appreciate your help.

**Comment by jumanamirza** [comment]
Dear Coracin,

Hope this message finds you well. First, I want to thank you again for your help when we were starting to work on LR-FHSS. I am writing to you with a quick update that we have released our software implementation of an LR-FHSS receiver at

[https://github.com/jumanamirza/LR-FHSS-receiver](https://urldefense.com/v3/__https://github.com/jumanamirza/LR-FHSS-receiver__;!!PhOWcWs!0FXOBRUMFswdVEvYmRyc2veQ2JPZ3-wNdUEFNTfkOtDw1V042zrZr-jR4aZX_lgmtgnk1JFFpbvJA0OUvg$)

Our receiver can detect and decode packets transmitted by a real LR-FHSS transmitter (SX1261). More information can be found in our report at

[https://arxiv.org/abs/2312.13981](https://urldefense.com/v3/__https://arxiv.org/abs/2312.13981__;!!PhOWcWs!0FXOBRUMFswdVEvYmRyc2veQ2JPZ3-wNdUEFNTfkOtDw1V042zrZr-jR4aZX_lgmtgnk1JFFpbuv8eSonA$)

Our findings confirm that LR-FHSS achieves high network capacity.  To our best knowledge, except Semtech, ours is the first work that obtains results with real-world packet traces.

Please feel free to let me know if you have any questions.

Best regards,
Jumana
