### ISSUE TITLE
sx1302_hal ERROR: AGC fw read/write check failed ERROR: Failed to load calibration fwERROR: radio calibration failedERROR: failed to start the gateway

### ISSUE THREAD

**Issue by iborntowin** [Lora-net/sx1302_hal#118]
I have this issue in lora gateway packet forwarder 
ERROR: AGC fw read/write check failed ERROR: Failed to load calibration fwERROR: radio calibration failedERROR: failed to start the gateway

![2b8c537e-3287-4d62-b47b-bd01fffd5e9f](https://github.com/Lora-net/sx1302_hal/assets/96054392/69a31eb9-32e8-48fb-85d3-8ca23bf7e825)

**Comment by mcoracin** [comment]
Hello @iborntowin ,
Do you still have this issue ?
If yes, could you prove more details about the hardware you are using ?

**Comment by iborntowin** [comment]
Hello @mcoracin, thank you for the response, I was using the wrong folder, I should work with packet_forwarder instead.
It works good now.
