### ISSUE TITLE
Gateway Sx1302 reboots unexpectedly when Tx downlink RX2 869.525MHz

### ISSUE THREAD

**Issue by Huydatnguyen** [Lora-net/sx1302_hal#121]
Hi everyone,

I am working with my gateway Waveshare SX1302_HAL, STM32WLE5 end-device OTAA, TTS Sandbox. The gateway library is https://github.com/Lora-net/sx1302_hal, version 2.1.0. The uplink and downlink RX1 work fine. However, when trying to send downlink RX2 in freq 869.525MHz, the gateway reboots itself unexpectedly. This downlink eventually still reaches the end-node but the packet forwarder does not work anymore.

![Screenshot_20240425_150434](https://github.com/Lora-net/sx1302_hal/assets/116315166/52b7bc98-46e9-4e31-bac7-98ca9314cf96)

Can you help me with this issue?
Thanks in advance.

**Comment by mcoracin** [comment]
Hello,
Does it happen everytime on RX2 ?
From the gateway point of view, it doesn't care about RX1 or RX2, it just sends at the time specified by the LNS.
But the radio parameters change, so maybe something is wrong with the Waveshare board, I've never used it.
Maybe it would be worth adding some debug logs to understand where it crashes. Is it in the packet forwarder, or in the sx1302 hal ?
For example enabling DEBUG_HAL and DEBUG_SX1302 in libloragw/library.cfg file could help seeing more details.
You'll need to recompile everything after changing this file.

**Comment by Huydatnguyen** [comment]
Thanks for your quick reply.
The problem is from the power supply. When I try to send a downlink in SF9BW125, it demands 27dBm by default. But my raspberry seems cannot suffer it and reboots ifself.  Solution might be to change the tx_gain_lut on global_config.json.
