### ISSUE TITLE
Using SPI on the SX1302CSS868GW1 reference design 

### ISSUE THREAD

**Issue by emanuelbuholzer** [Lora-net/sx1302_hal#123]
Hi,

Thanks a lot for the great work on the sx1302_hal. I'm currently using the Semtech Corecell reference design (SX1302CSS868GW1) over USB with the Raspberry PI and would like to evaluate the SPI interface. 

The User Guide states, that the LoRa gateway supports USB and SPI interfaces to connect to a Raspberry Pi host computer. Thus I expected the reference design to be suited for evaluating the SPI interface. Looking at the schematic below, I see that the SPI lines are not connected to the mPCIe connector, e.g. R316, R317, R318 and R319. 
￼
<img width="611" alt="UIM_PWR" src="https://github.com/Lora-net/sx1302_hal/assets/12075322/14edd990-5026-4194-9a57-43494ff6cf73">

Looking at the PCB in the picture below, these resistors are indeed not connected, but solder pads exist. Please note I only traced MISO to these solder pads, where I could see MISO is connected to the SPI-USB bridge, but not to the connection towards the mPCIe connector.

<img width="632" alt="Screenshot 2024-06-07 at 08 59 46" src="https://github.com/Lora-net/sx1302_hal/assets/12075322/a404f9e0-0643-4b7e-9a29-a4dc2959552b">
￼
 

Does the reference design officially support the SPI interface or should another module be used? If it does, is there any guidance on how to implement it? The solder pads seem quite small; I assume they are intended for metric 0402 resistors. 

Thanks a lot for any idea, thoughts or pointers!

**Comment by mcoracin** [comment]
Hello @emanuelbuholzer , as far as I know, the USB version of the reference design is not intended to support direct SPI interface, and would require hardware modification to be converted.
