### ISSUE TITLE
"foff" calculated method 

### ISSUE THREAD

**Issue by guo652917087** [Lora-net/sx1302_hal#2]
1.  my config:
{
    "SX130x_conf": {
        "spidev_path": "/dev/spidev0.0",
        "lorawan_public": true,
        "clksrc": 0,
        "antenna_gain": 0, /* antenna gain, in dBi */
        "full_duplex": false,
        "precision_timestamp": {
            "enable": false,
            "max_ts_metrics": 255,
            "nb_symbols": 1
        },
        "radio_0": {
            "enable": true,
            "type": "SX1250",
            "freq": 481800000,
            "rssi_offset": -207.0,
            "rssi_tcomp": {"coeff_a": -0.004, "coeff_b": 0.562, "coeff_c": -8.166, "coeff_d": 1224.528, "coeff_e": 11990.495},
            "tx_enable": true,
            "tx_freq_min": 470000000,
            "tx_freq_max": 510000000,
            "tx_gain_lut":[
                {"rf_power": -6, "pa_gain": 0, "pwr_idx":  0, "dig_gain": 0},
                {"rf_power": -3, "pa_gain": 0, "pwr_idx":  1, "dig_gain": 0},
                {"rf_power":  0, "pa_gain": 0, "pwr_idx":  2, "dig_gain": 0},
                {"rf_power":  3, "pa_gain": 1, "pwr_idx":  3, "dig_gain": 0},
                {"rf_power":  6, "pa_gain": 1, "pwr_idx":  4, "dig_gain": 0},
                {"rf_power": 10, "pa_gain": 1, "pwr_idx":  5, "dig_gain": 0},
                {"rf_power": 11, "pa_gain": 1, "pwr_idx":  6, "dig_gain": 0},
                {"rf_power": 12, "pa_gain": 2, "pwr_idx":  7, "dig_gain": 0},
                {"rf_power": 13, "pa_gain": 1, "pwr_idx":  8, "dig_gain": 0},
                {"rf_power": 14, "pa_gain": 3, "pwr_idx":  9, "dig_gain": 0},
                {"rf_power": 17, "pa_gain": 3, "pwr_idx": 15, "dig_gain": 0},
                {"rf_power": 20, "pa_gain": 3, "pwr_idx": 11, "dig_gain": 0},
                {"rf_power": 23, "pa_gain": 3, "pwr_idx": 12, "dig_gain": 0},
                {"rf_power": 25, "pa_gain": 3, "pwr_idx": 13, "dig_gain": 0},
                {"rf_power": 26, "pa_gain": 3, "pwr_idx": 14, "dig_gain": 0},
                {"rf_power": 27, "pa_gain": 3, "pwr_idx": 15, "dig_gain": 0}
            ]
        },
        "radio_1": {
            "enable": true,
            "type": "SX1250",
            "freq": 482600000,
            "rssi_offset": -207.0,
            "rssi_tcomp": {"coeff_a": -0.004, "coeff_b": 0.562, "coeff_c": -8.166, "coeff_d": 1224.528, "coeff_e": 11990.495},
            "tx_enable": false
        },
        "chan_multiSF_0": {"enable": true, "radio": 0, "if": -300000},
        "chan_multiSF_1": {"enable": true, "radio": 0, "if": -100000},
        "chan_multiSF_2": {"enable": true, "radio": 0, "if":  100000},
        "chan_multiSF_3": {"enable": true, "radio": 0, "if": -300000},
        "chan_multiSF_4": {"enable": true, "radio": 1, "if": -300000},
        "chan_multiSF_5": {"enable": true, "radio": 1, "if": -100000},
        "chan_multiSF_6": {"enable": true, "radio": 1, "if":  100000},
        "chan_multiSF_7": {"enable": true, "radio": 1, "if":  300000},
        "chan_Lora_std":  {"enable": true, "radio": 1, "if": -200000, "bandwidth": 250000, "spread_factor": 7,
                           "implicit_hdr": false, "implicit_payload_length": 17, "implicit_crc_en": false, "implicit_coderate": 1},
        "chan_FSK":       {"enable": true, "radio": 1, "if":  300000, "bandwidth": 125000, "datarate": 50000}
    },

    "gateway_conf": {
        "gateway_ID": "AA555A0000000000",
        /* change with default server address/ports */
        "server_address": "127.0.0.1",
        "serv_port_up": 1700,
        "serv_port_down": 1700,
        /* adjust the following parameters for your network */
        "keepalive_interval": 10,
        "stat_interval": 30,
        "push_timeout_ms": 100,
        /* forward only valid packets */
        "forward_crc_valid": true,
        "forward_crc_error": false,
        "forward_crc_disabled": false,
        /* GPS configuration */
        "gps_tty_path": "/dev/ttyUSB0",
        /* GPS reference coordinates */
        "ref_latitude": 0.0,
        "ref_longitude": 0.0,
        "ref_altitude": 0,
        /* Beaconing parameters */
        "beacon_period": 128,
        "beacon_freq_hz": 508300000,
        "beacon_datarate": 10,
        "beacon_bw_hz": 125000,
        "beacon_power": 14,
        "beacon_infodesc": 0
    },

    "debug_conf": {
        "ref_payload":[
            {"id": "0xCAFE1234"},
            {"id": "0xCAFE2345"}
        ],
        "log_file": "loragw_hal.log"
    }
}

2. I have a log like this：

CH0:    0       0       616     84      5133    14013   234     6128
CH1:    0       0       624     79      5214    13835   330     6280
CH2:    0       0       593     96      5186    13825   233     6386
CH3:    0       0       614     84      5139    14017   234     6130
CH4:    0       0       662     96      5178    13902   250     6239
CH5:    0       0       631     83      5201    13967   230     6316
CH6:    0       0       619     84      5111    13944   239     6326
CH7:    0       0       638     79      5272    13812   226     6305
CH8:    0       0       0       0       0       0       0       0
FSK:    0
Total number of LoRa packet received: 210517
Total number of FSK packet received: 0
Total number of LoRa packet received from 0xCAFE1234: 0
Total number of LoRa packet received from 0xCAFE2345: 0

JSON up: {"rxpk":[{"jver":1,"tmst":3897288465,"time":"2019-09-27T10:11:00.264327Z","tmms":1253614279264,"chan":5,"rfch":1,"freq":482.500000,"mid": 8,"stat":1,"modu":"LORA","datr":"SF10BW125","codr":"4/5","rssis":-63,"lsnr":12.5,"foff":-3362,"rssi":-62,"size":18,"data":"gPp4oQEAFtss6GNpmtthP3Ca"}]}

My question is: "foff":-3362, how is it calculated?  【 foff | number | LoRa frequency offset in Hz (signed interger) 】

My understanding: the data packet frequency of the log is: 482.500000MHz, the calculation method should be (482.6 - 0.1)MHz, chan is 5, and foff should be -100000 Hz.

**Comment by mcoracin** [comment]
foff is given by the sx1302 itself. It is the frequency offset computed by the hardware compared to the frequency given as configuration for a particular channel
