### ISSUE TITLE
Branch master-fdd-cn490

### ISSUE THREAD

**Issue by myfreescalewebpage** [Lora-net/sx1302_hal#25]
Hello,
Question about the branch master-fdd-cn490 and the release made here: is this branch tested ? Is it stable ?
Why isn't it merged on master branch and why the tags 1.1.0, 1.1.1 and 1.1.2 have no release (the last one today is 1.05) ?
Thanks for the answer,
Joel

**Comment by mcoracin** [comment]
Hello,
The master-fdd-cn490 branch has been tested for full-duplex CN490 region only. It is rather considered as a preliminary release for specific users who needed the Full Duplex support in the China 490MHz region.
It will be integrated in the master branch with a later release.
Best regards
