### ISSUE TITLE
CoreCell Interface board

### ISSUE THREAD

**Issue by kungccm** [Lora-net/sx1302_hal#3]
Hi Sir,

How can I buy the CoreCell Interface board?
Thanks a lot.

**Comment by jrclemmer** [comment]
Mouser or Digikey
https://octopart.com/search?q=sx1302c*gw1&currency=USD&specs=0

**Comment by vanthome** [comment]
What do you mean by that? We (n-fuse) are currently working on an SX1302 corecell based design and we have an interface board that breaks out all the needed signals (USB, SPI, I2C, PPS + SWD for Debugging). If you are interested in this, please contact me.
