### ISSUE TITLE
Packet Drop, USB vs SPI

### ISSUE THREAD

**Issue by karthiclodpi** [Lora-net/sx1302_hal#30]
Hi,

There is some Packet Drop when comparing USB vs SPI Version. USB version has Packet Drop when compared with SPI Version

Thanks,
KarthiG.

**Comment by mcoracin** [comment]
Hello,
It is not what we have seen during our tests.
Could you describe your test environment and test sequences for this comparison ?
Best regards,
Michael

**Comment by karthiclodpi** [comment]
Sorry, I have missed something in the configuration.

**Comment by chungwinn** [comment]
Hi @karthiclodpi would you mind elaborating on the issue you had with the config causing the usb packet drop if you can still remember? I am facing the same issue and am trying to troubleshoot it currently.
