### ISSUE TITLE
Can we set TX_JIT_DELAY to 60ms?

### ISSUE THREAD

**Issue by jerryyip** [Lora-net/sx1302_hal#38]
In our system, packet forwarder sometimes gets TX_SCHEDULED error after lgw_send() called, at about 0.3 percent chance. We think the reason of this is packet forwarder doesn't program the DOWN packet to the concentrator in time.  
If we can set TX_JIT_DELAY large, for example: 60ms, thread_jit will have more time to program the DOWN packet to the concentrator, then TX_SCHEDULED error will disappear.

But we don't know what adverse effects will be caused by changing TX_JIT_DELAY, could anyone tell us? Thanks for your help!

**Comment by mcoracin** [comment]
This parameter can be adjusted depending on your system load and SPI transfer speed, so I would say that yes, if on your system you see that 40ms is too short, you can increase it.
