### ISSUE TITLE
Can i use sx1302 recevie common LoRa packet(not LoRaWAN packet)?If yes,how do i modify the fireware and the end-node?

### ISSUE THREAD

**Issue by RT-Trio** [Lora-net/sx1302_hal#39]
I'm using RPI and sx1302 to build a test platform,then i'm using syncword PUBLIC and the end-node get the same syncword(0x34).But i can't recevie any packet but LoRaWAN packet.How i modify the fireware to fetch the common LoRa packet?

**Comment by mcoracin** [comment]
A LoRaWAN packet is just a LoRa packet with a particular payload.
The gateway does not parse the payload, it is LoRaWAN "agnostic".

But by default the gateway is configured to receive packets with 0x34 syncword, and non-inverted chirps.

If your gateway does not receive the LoRa packets sent by your end-node, you need to check the modulation parameters used by your end-node.
