### ISSUE TITLE
How to perform continuous output with LORA modulation enabled.

### ISSUE THREAD

**Issue by reissjason** [Lora-net/sx1302_hal#41]
The Sx1301 HAL utiliities have util_tx_continuous for CW, LORA and FSK modulations.
The test_loragw_hal_tx utility can perform a continuous CW but only output LORA and FSK in packet mode.
The certifications lab is requesting a 100% duty-cycle signal to measure Power Spectral Density.

**Comment by mcoracin** [comment]
You can use test_loragw_hal_tx, with a very long preamble size (65535). Used with SF12, it will last several minutes.
This is how we simulate a continuous TX internally.

**Comment by reissjason** [comment]
Thank you Michael, we will give that a try.

**Comment by reissjason** [comment]
This works as described, thanks!
