### ISSUE TITLE
failed to patch sx1261 radio for LBT/Spectral Scan

### ISSUE THREAD

**Issue by skyarm** [Lora-net/sx1302_hal#44]
SX1261: PRAM version: SX1268 V2F 2F06
SX1261: PRAM version: SX1268 V2F 2F06
ERROR: SX1261 PRAM version mismatch (got:2F06 expected:2D06)
ERROR: failed to patch sx1261 radio for LBT/Spectral Scan

**Comment by mcoracin** [comment]
Hello,
sx1268 is not supported, only sx1261 is.

**Comment by skyarm** [comment]
Thank you,  The China version hardware of 1302 Gateway Is not supported LBT, Because the sx1268 IO0 is not connected to 1302 GPIO7. So the sx1278 of this version hardware can only be used as downlink radio.
  I read the hardware reference of this version hardware design recent, It is designed  for a modem of downlink.
  Thanks again.

发自我的iPhone

在 2021年5月18日，15:24，Michael Coracin ***@***.***> 写道：

﻿

Hello,
sx1268 is not supported, only sx1261 is.
