### ISSUE TITLE
Same uplink but two rxpk

### ISSUE THREAD

**Issue by emanuele-dedonatis** [Lora-net/sx1302_hal#48]
I'm using a SX1302C868GW1 and trying different devices (STM B-L072Z-LRWAN1 with LoRaMAC-node too) but most of the time the gateway is sending to the LNS two rxpk with different frequencies for the same uplink. 

`JSON up: {"rxpk":[{"jver":1,"tmst":1087514388,"chan":4,"rfch":0,"freq":867.300000,"mid": 1,"stat":1,"modu":"LORA","datr":"SF12BW125","codr":"4/5","rssis":-110,"lsnr":-11.0,"foff":-1732,"rssi":-100,"size":23,"data":"QPk1ASYAAQDLeGWe3Vtlz/jFaY8ZpnA="},{"jver":1,"tmst":1087514390,"chan":1,"rfch":1,"freq":868.300000,"mid": 0,"stat":1,"modu":"LORA","datr":"SF12BW125","codr":"4/5","rssis":-35,"lsnr":11.0,"foff":-1733,"rssi":-35,"size":23,"data":"QPk1ASYAAQDLeGWe3Vtlz/jFaY8ZpnA="}]}`

Is it something related to the radio configuration? I'm using _global_conf.json.sx1250.EU868_

**Comment by emanuele-dedonatis** [comment]
Just found the issue:
it happens when the device is too close to the gateway

**Comment by wong-hao** [comment]
I have had the same problem.

The answer to most forums is too close.
