### ISSUE TITLE
Transmitting at 1.5x requested frequency?

### ISSUE THREAD

**Issue by MTMichaelB** [Lora-net/sx1302_hal#52]
I'm the electrical engineer on a project. As part of EMC testing, we found that for the first time after our system boots up, when I use test_loragw_hal_tx to transmit, it transmits at the requested frequency as well as at 1.5x the requested frequency. If I Ctrl+C kill the process and start it again, the 1.5x frequency isn't there anymore. Continued repeats of the command also do not send the 1.5x frequency. If I warm reboot the system, the 1.5x frequency comes back for the first run of the command.

I'm using this command to transmit rather continuously:
./test_loragw_hal_tx -f 925.1 -r 1250 -m LORA -n 10000 -s 12 -b 500 -z 255 --pwid 16 -l 65535 -t 50

We are using release v2.0.1.

Does this sound like an issue that others have seen?

Thank you.

**Comment by kmuster-semtech** [comment]
I am unable to reproduce this on my [SX1302CSS915GW1](https://www.semtech.com/products/wireless-rf/lora-core/sx1302cssxxxgw1). Could you share the concentrator board number or the product?
