### ISSUE TITLE
No documentation to calculate RSSI in dBm for SX1302 + SX1250

### ISSUE THREAD

**Issue by nilesh-dryad** [Lora-net/sx1302_hal#54]
I am using Semtech LoRa® Corecell reference design V1.0 (which has SX1302 and SX1250) and testing Receive and Transmit examples. While receiving packets, packet information are printed on console which has RSSI channel and RSSI signal value but those values are in dB.

Is there any equation to convert those values in dBm? I tried to find the information in source code and documents from Semtech website but all in vain.

**Comment by kmuster-semtech** [comment]
There are plots and an explanation of this in the [Performance Report resource](https://semtech.my.salesforce.com/sfc/p/#E0000000JelG/a/2R000000HUdh/9kR4.s9sZG5.CVW2ZrQOxjKl1FjKzwfh5k547K.M5Uc), Section 9 in the US report. With proper "rssi_offset" in the global_config.json file, the RSSI values can be interpreted as the received signal power level in dBm seen at the RFIO port.

**Comment by nilesh-dryad** [comment]
@kmuster-semtech
Thank you for your reply.
 How can I find that proper RSSI offset? is it fixed -215.4 for SX1302+ SX1250?

**Comment by kmuster-semtech** [comment]
> "How can I find that proper RSSI offset?"

The RSSI Offset value is found by calibration, shown in the CoreCell V1 Performance Report I linked earlier. The default value should be proper for any Corecell V1, but you may perform the calibration yourself and update the global_conf.json file of the packet forwarder.
