### ISSUE TITLE
Meaning of RSSI values 

### ISSUE THREAD

**Issue by jkbmtx** [Lora-net/sx1302_hal#6]
Hello all,

recently I have been doing some testing with test_loragw_hal_rx.
I usually get output that looks like this:

----- LoRa packet -----
  count_us: 6233679
  size:     23
  chan:     5
  status:   0x10
  datr:     7
  codr:     1
  rf_chain  0
  freq_hz   868100000
  snr_avg:  9.8
  rssi_chan:117.0
  rssi_sig :116.0
  crc:      0xFBA4

The RSSI values are however somewhat unclear for me. Normally I would expect the value to be somewhere around -110/-130 dBm, yet here the value is a positive number, which goes down as the signal gets weaker. For weak signals RSSI value is around 94. Could you maybe explain to me how to interpret those values?

Thank you.

**Comment by mcoracin** [comment]
Hello,
The RSSI values given by default, are the values without any RSSI offset applied.
To get the actual value, you have to add the -o option with the RSSI offset value corresponding to your board design.
For example, we use a value of -215.4 in the packet forwarder global_conf.json file.
Best regards,
Michael
