### ISSUE TITLE
CN490 configuration mismatch

### ISSUE THREAD

**Issue by joelguittet** [Lora-net/sx1302_hal#64]
Hello

I just compared the CN490 and CN490 USB configuration as shown below, and there is large differences at the radio configuration level. Why ?

![cn490_diff](https://user-images.githubusercontent.com/6479682/136698756-73f3669c-bec8-4ba0-944d-102deb75c0c2.PNG)

Thanks,
Joel

PS : some remark for the CN490.full-duplex config file template.

**Comment by mcoracin** [comment]
Hello, the board used for validating the USB and SPI versions were not the same, and those parameters have to be calibrated for the board design used. Hence the difference here. But I'll review that with CN team.

But anyway, this has to be calibrated on your side with the gateway design you are using.

For the full-duplex reference design is completely different form the half-duplex one. The front-end radio used are different (sx1255 vs sx1250).

Which gateway/reference design are you using ?

Best regards,
Michael

**Comment by joelguittet** [comment]
Hello

Thanks for the answer. I wasn't aware the differences can be so large.

For the RSSI and RF power data I can understand that. But why the frequencies are different ?

Currently using RAK2287 EU868/US915 version but targeting other models.

Joel

PS : how do you do calibration ? Do you have a good reference to share ?
