### ISSUE TITLE
Can SX1302 forward the recieved packet to another LoRaWan Gateway?

### ISSUE THREAD

**Issue by rickylkk** [Lora-net/sx1302_hal#73]
Hi,
I am a newbie in LoRaWan and I have a project that requires the sensor data to pass through one SX1320 to another LoraWan Gateway. Can I modify the code or settings to achieve this?
Sorry for inconviences.
Thanks.

**Comment by nilesh-dryad** [comment]
Hi @rickylkk Can I know why do you want to do this? What is the purpose?

**Comment by martyrs** [comment]
probably to cheat helium network @nilesh-dryad
