### ISSUE TITLE
Is the source code of STM32 available?

### ISSUE THREAD

**Issue by kahlenberg** [Lora-net/sx1302_hal#74]
Hi,

There is only host application to load binary to STM32, but there is no source code for STM32?

Thanks.

**Comment by mcoracin** [comment]
Hi,
The source code running on the STM32 (USB-SPI bridge), is available here:
[https://github.com/Lora-net/sx1302_spi_usb_bridge](https://github.com/Lora-net/sx1302_spi_usb_bridge)
Best regards
