### ISSUE TITLE
Unable to get two corecell units to communicate with each other

### ISSUE THREAD

**Issue by delhiryder** [Lora-net/sx1302_hal#96]
Hi, 

We are working on a LoRa based project, with the Sx1302 based Corecell Dev Kit as the staging platform. As part of the development, we are trying to get two of these units to communicate with one another.

I have tried various permutations of the test_loragw_hal_rx method (the latest iteration, for Corecell Unit 1, the receiver, is below):

```
./test_loragw_hal_rx -u -d /dev/ttyACM0 -k 1 -r 1250 -b 905 -o -215.4 -n 10 -z 5 -m 0  -j
```

The call to the _tx utility (which is running on Corecell Unit 2, the transmitter) is below:

```
./test_loragw_hal_tx -u -d /dev/ttyACM0 -k 0 -c 0 -r 1250 -f 904.3 -m LORA -s 7 -b 250 -l 8 -n 100 -z 16 -t 500 --pa 1 --pwid 0
```

When I call these methods (first on the RX Corecell, and then on the TX Corecell), nothing happens.

Is there some additional configuration that needs to be added/changed ?

Any help is greatly appreciated.

Regards,

Sidd

p.s. I have tried to transmit in the so called 'inverted modulation polarity', but that does not appear to make any difference here.

**Comment by mcoracin** [comment]
Hi @delhiryder,

Few questions:
- why are you using -k 1 on the RX gateway ? Are you using same type of hardware for the RX gateway and the TX gateway ? If both are corecell reference design, you should use -k 0 for both.
- The TX command line shows a 250 KHz bandwidth. There is only 1 channel on the gateway which can receive 250 KHz (the LoRaStd channel), are you sure that it is configured with the frequency you are using for TX ?

When sending a LoRa packet to be received by a gateway, you must not use inverted polarity.

Best regards,
Michael

**Comment by mcoracin** [comment]
No answer, I close this issue. Feel free to reopen it if needed.
