### ISSUE TITLE
local_conf.json never gets parsed

### ISSUE THREAD

**Issue by shawaj** [Lora-net/sx1302_hal#98]
not sure if this is intentional, but the docs mention a local_conf.json but if you actually use one, it never gets parsed.

is this by design?

**Comment by mcoracin** [comment]
Which doc are you referring to ?
I don't think there is any reference to a local_conf.json in this repository, right ?

Thanks

**Comment by shawaj** [comment]
@mcoracin yes it is mentioned in packet forwarder readme

**Comment by shawaj** [comment]
Here is link...
https://github.com/Lora-net/sx1302_hal/tree/master/packet_forwarder#4-usage

**Comment by mcoracin** [comment]
Thanks @shawaj , we will fix this with next release.

**Comment by shawaj** [comment]
Great thanks
